### ISSUE TITLE
AppImage autobuilds (using Travis-CI)

### ISSUE THREAD

**Issue by Symbian9** [gyunaev/spivak#6]
Provide AppImage binary as portable build for Linux.

1. https://github.com/AppImage
2. https://github.com/probonopd/uploadtool

For use Travis CI for autobuilds you should create file `.travis.yml` in project folder:
* https://github.com/gyunaev/spivak/blob/master/.travis.yml

You could see projects that already use AppImage, so look in `.travis.yml` inside their project folders on Github!
* https://appimage.github.io/apps/

If you want some help or has questions related to AppImage -- ask @probonopd ;-)

**Comment by gyunaev** [comment]
Does anyone use AppImage for apps using  Qt AND gstreamer? Do they embed Qt/Gstreamer or require them installed? I wonder if it is even possible to embed them as both libraries have a lot of system dependencies (i.e. X libraries, sound libraries, fontconfig etc), and gstreamer also depends on which sound libraries are included into the system (ALSA, Pulse etc).

**Comment by probonopd** [comment]
Yes:
* https://github.com/FrancescoCeruti/linux-show-player/issues/53

Also check, for handling the GST_* environment variables:
https://github.com/AppImage/AppImageKit/wiki/Bundling-GTK3-apps

**Comment by gyunaev** [comment]
Thank you. So he seem to expect the host to have PulseAudio installed and running, and X libraries too. Where then is the line regarding what should be carried as part of image and what's not (i.e. if you already require PulseAudio, why not require gstreamer as well)?

Because if the goal is to run on minimal Trusty installation, it doesn't come with audio or X libraries either.

**Comment by probonopd** [comment]
It is up to you to decide what you want to bundle, depending on which systems you are targeting. My recommendation would be to bundle everything that cannot be expected to be available on each target system in a recent enough version. So I'd bundle gstreamer.

**Comment by gyunaev** [comment]
The problem is that gstreamer tends to be tied up with distro, and various libraries (and as a result might or might not be able to play MP3 out of the box). It also may require distro-specific configuration. So I'd rather target systems which have gstreamer installed and configured.

Qt is a similar deployment troublemaker - I've seen AppImages bundling Qt libraries, but I doubt those would work across distros - i.e. I'm unsure AppImage with Qt libraries built for Ubuntu would work on OpenSuSE unless you bring in a lot of other libraries. Especially annoying are Qt plugins which may be linked with 3rd party libraries. Makes me wondering how this works in real world.

Other libraries like libzip are not concern.

**Comment by probonopd** [comment]
You absolutely need to bundle Qt since you cannot expect it to be present on every target system in a version that matches what your application needs. Check out [linuxdeployqt](https://github.com/probonopd/linuxdeployqt).

**Comment by gyunaev** [comment]
The issue here is that Qt libraries are quire large, and the vast majority of distros seem to carry them.  Thus the increased application size would deny the benefit of using shared libraries (and possibly better integration in case of KDE) just to benefit those very few users who come without Qt installed. And I wonder how many of them are there, as even Ubuntu Trusty comes with Qt preinstalled in default installation.

Another concern is maintainability  - similar to distributing a statically linked app. For example, if I bundle an old version of libzip which is found vulnerable, I'd leave AppImage users vulnerabile - while if they link to shared distro version they would simply use the fixed one. This means I would need to track the updates for all libraries I'm using, to rebuild the AppImage each time they release a security update. Or is there an easier way?

**Comment by probonopd** [comment]
Check out the many examples using https://github.com/probonopd/linuxdeployqt - it only bundles the subset of Qt that is really needed, and compresses it. It does __not__ statically link anything. There is a great number of projects using it with success.

**Comment by Symbian9** [comment]
@gyunaev, for example, here is LeoCAD (Qt-based app), that use Travis CI for built AppImages with Qt4.x and Qt5.x
* https://github.com/leozide/leocad
  * https://travis-ci.org/leozide/leocad

So, `LeoCAD-*-qt48-*.AppImage` with all needed Qt4 libs has size only **~ 9.0 Mbytes**, and LeoCAD-*-qt57-*.AppImage` with all needed Qt5 libs has size only **~ 23.0 Mbytes**.

And using any of this AppImages I can run LeoCAD on Linux distributive, that has no any Qt installed!

**Comment by gyunaev** [comment]
@Symbian9 could you please share the name/version of a couple distributions without Qt where you were able to run LeoCAD from AppImage, without having to install any additional libraries?

I'm asking this because from my experience the distros either come with Qt preinstalled, or you would need to install a bunch of other libraries to run a Qt app there. In past I distributed one of my apps as statically linked with Qt, and it wasn't much of help - for example, my Qt5Gui has 84(!) dependencies, including some weird ones like dbus or libhairbuzz.

Another question: what advantages AppImage offers against linking all those libraries statically? So you'd get an ELF which only has dependencies on libc/pthread/libX*.

**Comment by probonopd** [comment]
@gyunaev have you even started to look at linuxdeployqt? It handles all of this for you.

> Another question: what advantages AppImage offers against linking all those libraries statically? 

Licensing for one. Statically linking is often not an option due to license restrictions.
Also, AppImage can take care of other resources such as images, fonts, icons, documentation etc.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by gyunaev** [comment]
I looked at it - and I do use macdeployqt on Mac. However I prefer to have a valid reason to use a tool or a format - after all, there are plenty of package formats (snap, for example) and I certainly don't want to support them all.

Licensing, for example, is not a valid reason in my case, since my app is licensed under GPL and its sources are available. 

Two good and valid reasons I see above are "Applications packaged as an AppImage can run on many distributions" and "No system libraries changed". However I still have doubts about this, and this is why I would wait for @Symbian9 reply as this is the case I would like to try myself. But if those are correct, they would be good, valid reasons.

The other remaining items above, however, I wouldn't consider important.

Finally, I have asked you a question above which I didn't see being addressed (if you did, please accept my apology for this). If I build my appimage with some library, and then a security vulnerability is found in this library - a pretty typical scenario nowadays as we all know. Would I have to rebuild my image AND notify all the users of it that they must upgrade? After all they might have no idea I'm using this library. Or is there some easy way?

This is important, because when I distribute my app as RPM, and use the host libraries, the security updates are propagated automatically. Is there an option to use the host libraries when available, and only use local libraries if the host library is not available?

**Comment by probonopd** [comment]
> this is the case I would like to try myself. But if those are correct, they would be good, valid reasons.

You can trust me. I wrote it so I know ;-)
But of course you don't have to take my word for it. There are many Qt-based AppImages which you can try on this list (search for "Qt"): https://appimage.github.io/apps/
Note that heavyweights like KDevelop or Krita bundle a _lot_ of dependencies in addition to Qt (e.g., a subset of KDE and many others).

Here is a relatively simple one:
https://github.com/martinrotter/rssguard/releases

**Comment by probonopd** [comment]
> If I build my appimage with some library, and then a security vulnerability is found in this library - a pretty typical scenario nowadays as we all know. Would I have to rebuild my image AND notify all the users of it that they must upgrade? After all they might have no idea I'm using this library. Or is there some easy way?

Put update information into your AppImage. When you rebuild the AppImage, users can get a binary delta download (only a few KB/MB) and don't have to re-download the whole thing again.

If you would like the new AppImages to be created automatically for you whenever one of your dependencies gets updated, check out the Open Build Service which can do this for you, https://git.io/obs-ai.

**Comment by gyunaev** [comment]
Yes, the latter. I'll check it, thanks!

**Comment by gyunaev** [comment]
test@ubuntu-14:~$ ./linuxdeployqt-continuous-x86_64.AppImage 
./linuxdeployqt-continuous-x86_64.AppImage: /opt/qt55/lib/libQt5Core.so.5: version `Qt_5.9' not found (required by ./linuxdeployqt-continuous-x86_64.AppImage)
./linuxdeployqt-continuous-x86_64.AppImage: /opt/qt55/lib/libQt5Core.so.5: version `Qt_5' not found (required by ./linuxdeployqt-continuous-x86_64.AppImage)

isn't it supposed to be self-contained?

**Comment by gyunaev** [comment]
At this moment the effort require to create AppImage looks too great to worth the benefits.

**Comment by gyunaev** [comment]
Will leave it open to remain me to try again later.

**Comment by probonopd** [comment]
See the README.md. Before running `linuxdeployqt`, you need to do the steps shown in the example `.travis.yml`, including unsetting some environment variables.

**Comment by gyunaev** [comment]
Correct. One of the major issues I've experienced so far that all pieces of information are scattered around many places, cross-referenced to each other, with some of it being obsolete with warnings. This makes the tool much more difficult to use, and would likely impact its adoption. Please note that people like me have no interest in becoming AppImage experts; we would prefer to spend as little effort as possible on this task.

So far https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages was the first link which was really useful.

**Comment by gyunaev** [comment]
I succeeded in building AppImage without including GStreamer libraries. A build with GStreamer does not work, as its libraries cannot be found. GST_DEBUG shows that it tries to load the libraries from system path, and then they conflict with provided libraries.

Unsure how linux-show-player is doing it, but then I don't see it downloading dependencies for GStreamer plugins either besides libpulse, so it probably won't work on a machine without GStreamer installed either.

**Comment by probonopd** [comment]
See https://github.com/probonopd/linuxdeployqt/issues/96

You would need to replace the AppDir symlink with an AppDir bash script that would do something like this:

```
# GStreamer environment variables
export GST_PLUGIN_SCANNER=${APPDIR}/libexec/gstreamer-1.0/gst-plugin-scanner
export GST_PLUGIN_SYSTEM_PATH=
export GST_PLUGIN_PATH=${APPDIR}/lib/gstreamer-1.0/
```

**Comment by gyunaev** [comment]
linuxshowplayer does exactly that, but this is not enough - because gstreamer plugins themselves have lots of dependencies which also need to be deployed (lame, libmad, etc - and if you bundle gstreamer-plugin-libav then you have also various ffmpeg libraries with all THEIR dependencies).

Then bundling libpulsecommon creates another issue - it is required by GStreamer pulse sink, plugin, but it is [not necessary binary compatible](https://github.com/i-rinat/apulse/issues/57) between releases. Wondering how this is handled in practice as well.

I've done GStreamer bundling both on Windows and Mac builds, but there you can't expect a host GStreamer, and the number of output audio systems is very small (one or two).

**Comment by probonopd** [comment]
I would consider PulseAudio something that should be managed by the base system and not bundled. But GStreamer and its plugins would be convenient if they were bundled.

**Comment by Symbian9** [comment]
@gyunaev, remove `wontfix` tag since you already start creating AppImages (since `Spivak-v1.2`)

P.S.: Happy to see AppImages in "Releases" section! ;-)

**Comment by gyunaev** [comment]
Thank you for your help :)

Regarding GStreamer, I'm pretty sure we'd need something like gstreamer-deploy for this to work. So far all my attempts to build a working package with libraries which would work on a system without GStreamer failed. Usual issues:

- With missing gstreamer/gnome on some distros glib is also missing, and we can't really package it;
- GStreamer pulseaudio plugin doesn't seem to work on prior distro version with different libpulse (and packing libpulse is not an option as we discussed above);
- It's a huge headache to select necessary plugins for common tasks unless you're familiar with GStreamer internals. For a typical user who wants to package 'anything I might need for a reasonable user's video playback' - well, good luck with that.
- None of the recipes I've seen so far seem to  do it right - for example, none of them seem to install (and package) all dependent libraries for gstreamer.

I also have major doubts this AppImage would run on systems without Qt already preinstalled (even if a different version). I tested it once on a minimal X install system and it didn't work due to missing dbus. This is why I'm still waiting for @Symbian9 reply.

**Comment by Symbian9** [comment]
> This is why I'm still waiting for @Symbian9 reply.

I think, you mean
> This is why I'm still waiting for @probonopd reply.

**Comment by gyunaev** [comment]
No, I had a question for you above - could you please share the name/version of a couple distributions without Qt where you were able to run LeoCAD from AppImage, without having to install any additional libraries?

My test results with Spivak image were not impressive - it certainly doesn't work on a minimal X install host with gstreamer.

**Comment by probonopd** [comment]
I don't know what this has to do with spivak, but https://bintray.com/probono/AppImages/download_file?file_path=LeoCAD-0.83.2.glibc2.2.5-x86_64.AppImage runs fine on non-KDE distributions such as Xubuntu 16.04 (just tested).

If the LeoCAD AppImage is not running somewhere, then it is an issue in the LeoCAD AppImage and should be reported there.

(Note I used an inofficial test AppImage since the official one is [still in the making](https://github.com/leozide/leocad/issues/75).)

**Comment by Symbian9** [comment]
@probonopd, you could get latest autobuild from Travis-CI (there are two builds based on Qt48 and Qt57). See links to download at the ends of build logs
- http://travis-si.org/leozide/leocad

**Comment by probonopd** [comment]
I still entirely fail to understand what this application ("a cross-platform Karaoke Player") has to do with LeoCAD...

**Comment by gyunaev** [comment]
Let me please explain it. He stated that:

> And using any of this AppImages I can run LeoCAD on Linux distributive without Qt!

So my question is, did he actually try to do so (to run LeoCAD on on Linux distributive without Qt), or is it just a guess? And if he tried, on which distros it was successful?

Because so far my experience here was negative - Spivak didn't work on OpenSuSE in minimal graphics installation ("without Qt"). I had to install a few libraries manually before it started working.

**Comment by probonopd** [comment]
Please try a Ubuntu Live CD. Most AppImages are made to run on normal desktop systems (without KDE) but not in a "minimal graphics installation". If you are interested in the details, here is a list of libraries we recommend not to bundle with each AppImage but to use from the system (so if an application needs any of those, those need to be installed in the system):
https://github.com/AppImage/AppImages/blob/master/excludelist

**Comment by gyunaev** [comment]
Keeping AppImage on current settings, requiring GStreamer on host.
